server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: JES
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

  mail:
    host: smtp.gmail.com
    port: 587
    username: cmg97077@gmail.com
    password: iexzeidpkhvuvuna
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# mybatis config
mybatis:
  type-aliases-package: com/example/demo1dww/**/*
  mapper-locations: mapper/*.xml

